export const CREATE = 'create'
export const MY_PROFILE_FETCH = 'myProfileFetch'
export const DELETE = 'delete'
export const EDIT = 'edit'
export const COMPLETE_STATUS = 'completeStatus'
export const PROJECTS_LOADING = 'projectsLoading'
export const TASKS_LOADING = 'tasksLoading'